=== wikimedia/mediawiki/docs/export-0.3.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<!--
	This is an XML Schema description of the format
	output by MediaWiki's Special:Export system.
	
	Version 0.2 adds optional basic file upload info support,
	which is used by our OAI export/import submodule.
	
	Version 0.3 adds some site configuration information such
	as a list of defined namespaces.
	
	The canonical URL to the schema document is:
	http://www.mediawiki.org/xml/export-0.3.xsd
	
	Use the namespace:
	http://www.mediawiki.org/xml/export-0.3/
-->
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:mw="http://www.mediawiki.org/xml/export-0.3/"
        targetNamespace="http://www.mediawiki.org/xml/export-0.3/"
        elementFormDefault="qualified">

	<annotation>
		<documentation xml:lang="en">
			MediaWiki's page export format
		</documentation>
	</annotation>
	
	<!-- Need this to reference xml:lang -->
	<import namespace="http://www.w3.org/XML/1998/namespace"
		schemaLocation="http://www.w3.org/2001/xml.xsd"/>
	
	<!-- Our root element -->
	<element name="mediawiki" type="mw:MediaWikiType"/>
	
	<complexType name="MediaWikiType">
		<sequence>
			<element name="siteinfo" type="mw:SiteInfoType"
				minOccurs="0" maxOccurs="1"/>
			<element name="page" type="mw:PageType"
				minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="version" type="string" use="required"/>
		<attribute ref="xml:lang" use="required"/>
	</complexType>
	
	<complexType name="SiteInfoType">
		<sequence>
			<element name="sitename" type="string" minOccurs="0" />
			<element name="base" type="anyURI" minOccurs="0" />
			<element name="generator" type="string" minOccurs="0" />
			<element name="case" type="mw:CaseType" minOccurs="0" />
			<element name="namespaces" type="mw:NamespacesType" minOccurs="0" />
		</sequence>
	</complexType>
	
	<simpleType name="CaseType">
		<restriction base="NMTOKEN">
			<!-- Cannot have two titles differing only by case of first letter. -->
			<!-- Default behavior through 1.5, $wgCapitalLinks = true -->
			<enumeration value="first-letter" />
			
			<!-- Complete title is case-sensitive -->
			<!-- Behavior when $wgCapitalLinks = false -->
			<enumeration value="case-sensitive" />
			
			<!-- Cannot have two titles differing only by case. -->
			<!-- Not yet implemented as of MediaWiki 1.5 -->
			<enumeration value="case-insensitive" />
		</restriction>
	</simpleType>
	
	<complexType name="NamespacesType">
		<sequence>
			<element name="namespace" type="mw:NamespaceType"
				minOccurs="0" maxOccurs="unbounded" />
		</sequence>
	</complexType>
	
	<complexType name="NamespaceType">
		<simpleContent>
			<extension base="string">
				<attribute name="key" type="integer" />
			</extension>
		</simpleContent>
	</complexType>
	
	<complexType name="PageType">
		<sequence>
			<!-- Title in text form. (Using spaces, not underscores; with namespace ) -->
			<element name="title" type="string"/>
			
			<!-- optional page ID number -->
			<element name="id" type="positiveInteger" minOccurs="0"/>

			<!-- optional: number of pages that link to this page -->
			<element name="references" type="positiveInteger" minOccurs="0"/>
			
			<!-- comma-separated list of string tokens, if present -->
			<element name="restrictions" type="string" minOccurs="0"/>
			
			<!-- Zero or more sets of revision or upload data -->
			<choice minOccurs="0" maxOccurs="unbounded">
				<element name="revision" type="mw:RevisionType" />
				<element name="upload" type="mw:UploadType" />
			</choice>
		</sequence>
	</complexType>
	
	<complexType name="RevisionType">
		<sequence>
			<element name="id" type="positiveInteger" minOccurs="0"/>
			<element name="timestamp" type="dateTime"/>
			<element name="contributor" type="mw:ContributorType"/>
			<element name="minor" minOccurs="0" />
			<element name="comment" type="string" minOccurs="0"/>
			<element name="text" type="mw:TextType" />
		</sequence>
	</complexType>
	
	<complexType name="TextType">
		<simpleContent>
			<extension base="string">
				<attribute ref="xml:space" use="optional" default="preserve" />
			</extension>
		</simpleContent>
	</complexType>
	
	<complexType name="ContributorType">
		<sequence>
			<element name="username" type="string" minOccurs="0"/>
			<element name="id" type="positiveInteger" minOccurs="0" />
			
			<element name="ip" type="string" minOccurs="0"/>
		</sequence>
	</complexType>
	
	<complexType name="UploadType">
		<sequence>
			<!-- Revision-style data... -->
			<element name="timestamp" type="dateTime"/>
			<element name="contributor" type="mw:ContributorType"/>
			<element name="comment" type="string" minOccurs="0"/>
			
			<!-- Filename. (Using underscores, not spaces. No 'Image:' namespace marker.) -->
			<element name="filename" type="string"/>
			
			<!-- URI at which this resource can be obtained -->
			<element name="src" type="anyURI"/>
			
			<element name="size" type="positiveInteger" />
			
			<!-- TODO: add other metadata fields -->
		</sequence>
	</complexType>
	
</schema>

=== wikimedia/mediawiki/tests/test-prefetch-current.xml
<mediawiki xmlns="http://www.mediawiki.org/xml/export-0.3/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mediawiki.org/xml/export-0.3/ http://www.mediawiki.org/xml/export-0.3.xsd" version="0.3" xml:lang="en">
<siteinfo>
  <sitename>DemoWiki</sitename>
  <base>http://example.com/wiki/Main_Page</base>
  <generator>MediaWiki 1.5.0</generator>
  <case>first-letter</case>
  <namespaces>
    <namespace key="-2">Media</namespace>
    <namespace key="-1">Special</namespace>
    <namespace key="0"></namespace>
    <namespace key="1">Talk</namespace>
    <namespace key="2">User</namespace>
    <namespace key="3">User talk</namespace>
    <namespace key="4">DemoWiki</namespace>
    <namespace key="5">DemoWIki talk</namespace>
    <namespace key="6">Image</namespace>
    <namespace key="7">Image talk</namespace>
    <namespace key="8">MediaWiki</namespace>
    <namespace key="9">MediaWiki talk</namespace>
    <namespace key="10">Template</namespace>
    <namespace key="11">Template talk</namespace>
    <namespace key="12">Help</namespace>
    <namespace key="13">Help talk</namespace>
    <namespace key="14">Category</namespace>
    <namespace key="15">Category talk</namespace>
  </namespaces>
</siteinfo>
<page>
  <title>First page</title>
  <id>1</id>
  <revision>
    <id>1</id>
    <timestamp>2001-01-15T12:00:00Z</timestamp>
    <contributor><ip>10.0.0.1</ip></contributor>
    <comment>page 1, rev 1</comment>
    <text>page 1, rev 1</text>
  </revision>
  <revision>
    <id>2</id>
    <timestamp>2001-01-15T12:00:00Z</timestamp>
    <contributor><ip>10.0.0.1</ip></contributor>
    <comment>page 1, rev 2</comment>
    <text>page 1, rev 2</text>
  </revision>
  <revision>
    <id>4</id>
    <timestamp>2001-01-15T12:00:00Z</timestamp>
    <contributor><ip>10.0.0.1</ip></contributor>
    <comment>page 1, rev 4</comment>
    <text>page 1, rev 4</text>
  </revision>
</page>
<page>
  <title>Second page</title>
  <id>2</id>
  <revision>
    <id>3</id>
    <timestamp>2001-01-15T12:00:00Z</timestamp>
    <contributor><ip>10.0.0.1</ip></contributor>
    <comment>page 2, rev 3</comment>
    <text>page 2, rev 3</text>
  </revision>
</page>
<page>
  <title>Third page</title>
  <id>3</id>
  <revision>
    <id>5</id>
    <timestamp>2001-01-15T12:00:00Z</timestamp>
    <contributor><ip>10.0.0.1</ip></contributor>
    <comment>page 3, rev 5</comment>
    <text>page 3, rev 5</text>
  </revision>
</page>
</mediawiki>
